const tourDates = [
  {
    id: 1,
    date: 'November 9, 2025',
    city: 'San diego, Ca',
    venue: 'Pechanga Arena San Diego',
    ticket: 'https://www.axs.com/events/1042810/tame-impala-tickets',
  },
  {
    id: 2,
    date: 'November 11, 2025',
    city: 'Inglewood, Ca',
    venue: 'Kia Forum',
    ticket: 'https://www.ticketmaster.com/event/090062EF005A68AA',
  },
  {
    id: 3,
    date: 'November 12, 2025',
    city: 'Inglewood, Ca',
    venue: 'Kia Forum',
    ticket: 'https://www.ticketmaster.com/event/09006322B61E6FB1',
  },
  {
    id: 4,
    date: 'November 14, 2025',
    city: 'Oakland, Ca',
    venue: 'Oakland Arena',
    ticket:
      'https://www.axs.com/events/1048957/tame-impala-tickets?skin=theoaklandarena',
  },
  {
    id: 5,
    date: 'November 15, 2025',
    city: 'Oakland, Ca',
    venue: 'Oakland Arena',
    ticket:
      'https://www.axs.com/events/1048958/tame-impala-tickets?skin=theoaklandarena',
  },
  {
    id: 6,
    date: 'November 17, 2025',
    city: 'Inglewood, Ca',
    venue: 'Kia Forum',
    ticket:
      'https://www.ticketmaster.com/tame-impala-deadbeat-tour-inglewood-california-11-17-2025/event/0900632AAB9E20C3',
  },

  {
    id: 7,
    date: 'April 4, 2026',
    city: 'Porto, Portugal',
    venue: 'Super Bock Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 8,
    date: 'April 5, 2026',
    city: 'Lisbon, Portugal',
    venue: 'Meo Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 9,
    date: 'April 7, 2026',
    city: 'Madrid, Spain',
    venue: 'Movistar Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 10,
    date: 'April 8, 2026',
    city: 'Barcelona, Spain',
    venue: 'Palau Sant Jordi',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 11,
    date: 'April 10, 2026',
    city: 'Lyon, France',
    venue: 'Ldlc Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 12,
    date: 'April 12, 2026',
    city: 'Turin, Italy',
    venue: 'Inalpi Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 13,
    date: 'April 13, 2026',
    city: 'Bologna, Italy',
    venue: 'Unipol Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 14,
    date: 'April 14, 2026',
    city: 'Zurich, Switzerland',
    venue: 'Hallenstadion',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 15,
    date: 'April 16, 2026',
    city: 'Munich, Germany',
    venue: 'Olympiahalle',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 16,
    date: 'April 18, 2026',
    city: 'Gliwice, Poland',
    venue: 'Prezero Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 17,
    date: 'April 20, 2026',
    city: 'Prague, Czech Republic',
    venue: 'O2 Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 18,
    date: 'April 23, 2026',
    city: 'Hamburg, Germany',
    venue: 'Barclays Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 19,
    date: 'April 25, 2026',
    city: 'Copenhagen, Denmark',
    venue: 'Royal Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 20,
    date: 'April 26, 2026',
    city: 'Stockholm, Sweden',
    venue: 'Avicii Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
  {
    id: 21,
    date: 'April 27, 2026',
    city: 'Oslo, Norway',
    venue: 'Unity Arena',
    ticket: 'https://tix.to/TIEurope26',
  },
];

export default tourDates;
